# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_download.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.urlEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.urlEdit.setGeometry(QtCore.QRect(20, 30, 401, 20))
        self.urlEdit.setObjectName("urlEdit")
        self.pasteButton = QtWidgets.QPushButton(self.centralwidget)
        self.pasteButton.setGeometry(QtCore.QRect(440, 10, 75, 23))
        self.pasteButton.setObjectName("pasteButton")
        self.tableURL = QtWidgets.QTableWidget(self.centralwidget)
        self.tableURL.setGeometry(QtCore.QRect(20, 70, 491, 261))
        self.tableURL.setObjectName("tableURL")
        self.tableURL.setColumnCount(1)
        self.tableURL.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableURL.setHorizontalHeaderItem(0, item)
        self.tableURL.horizontalHeader().setCascadingSectionResizes(True)
        self.tableURL.horizontalHeader().setStretchLastSection(True)
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(430, 340, 75, 23))
        self.downloadButton.setObjectName("downloadButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 340, 401, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.listMemo = QtWidgets.QListWidget(self.centralwidget)
        self.listMemo.setGeometry(QtCore.QRect(20, 370, 401, 181))
        self.listMemo.setObjectName("listMemo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label.setObjectName("label")
        self.findButton = QtWidgets.QPushButton(self.centralwidget)
        self.findButton.setGeometry(QtCore.QRect(440, 40, 75, 23))
        self.findButton.setObjectName("findButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pasteButton.setText(_translate("MainWindow", "Paste"))
        item = self.tableURL.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "URL"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.label.setText(_translate("MainWindow", "Enter url:"))
        self.findButton.setText(_translate("MainWindow", "Find file"))
